# -*- coding: utf-8 -*-
"""
/***************************************************************************
 vegetation_indices
                                 A QGIS plugin
 This plugin calculates vegetation indices
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-01-23
        copyright            : (C) 2024 by NurayB
        email                : nuraybas@cumhuriyet.edu.tr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load vegetation_indices class from file vegetation_indices.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .QSVI_Plugin import vegetation_indices
    return vegetation_indices(iface)
